### ISSUE TITLE
OneFlow fix zero在libai的回归测试

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/libai#150]
PR：https://github.com/Oneflow-Inc/oneflow/pull/7557

这个issue的方案已经确定，辛苦用这个分支试验一下（我这里已经验证通过）。

验证点：
1、zero的可以执行，就是issue的内容； @CPFLAME 
2、libai的混合并行，性能正常（这个改动涉及一个基础的sbp推理限制，想验证这个改动对性能没有负面影响）； @L1aoXingyu 

验证通过，就合并这个PR；

**Comment by CPFLAME** [comment]
这个分支在libai的`master`下经过测试:

目前可以跑通的配置:

- 数据并行+模型并行+流水并行
- 数据并行+流水并行+zero
- 数据并行+zero

目前报错的配置:
> zero是否不需要和模型并行一起开, 只需要和数据并行以及流水并行放在一起就够用了. 
- 模型并行+zero

复现错误的运行指令:
```shell
sh tools/train.sh configs/t5_pp_pretrain.py 8 train.dist.tensor_parallel_size=8 train.dist.pipeline_parallel_size=1 train.dist.data_parallel_size=1 train.zero_optimization.enabled=True train.zero_optimization.stage=3 train.log_period=1
```

错误信息

<details>


```
F20220301 16:13:36.679355 51722 exec_graph.cpp:117] 
  File "/home/chengpeng/data/oneflow/oneflow/core/graph/exec_graph.cpp", line 117, in InferBlobDescs
    op_->InferBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx, &GlobalJobDesc())
  File "/home/chengpeng/data/oneflow/oneflow/core/operator/operator.cpp", line 324, in InferBlobDescsIf
    InferOutBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx)
  File "/home/chengpeng/data/oneflow/oneflow/core/operator/user_op.cpp", line 599, in InferOutBlobDescs
    val_->physical_tensor_desc_infer_fn(&infer_ctx)
  File "/home/chengpeng/data/oneflow/oneflow/user/ops/reshape_op.cpp", line 101, in InferPhysicalTensorDesc
    Check failed: (out_shape->elem_cnt()) == (in_shape.elem_cnt()) (393216 vs 589824)  Reshape infer ERROR! in op_name: model.t5_model.decoder.layers.0.self_attention-reshape-285 input shape is : (32,128,144) , output shape is : (32,128,1,96) , output logical shape is (32,128,12,96) , And reshape shape conf is : (32,128,12,96) op_loc: Python stack[-2]: <frame at 0x561400c35d40, file '/home/chengpeng/data/oneflow/python/oneflow/framework/tensor.py', line 928, code _view>; Python stack[-1]: <frame at 0x561400c72950, file '/home/chengpeng/data/oneflow/python/oneflow/nn/modules/reshape.py', line 68, code view_op>; C API: <func reshape>
*** Check failure stack trace: ***
    @     0x7f3e402c164d  google::LogMessage::Fail()
    @     0x7f3e402c384c  google::LogMessage::SendToLog()
    @     0x7f3e402c10ea  google::LogMessage::Flush()
    @     0x7f3e402c4229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3e4547dfe1  oneflow::ExecNode::InferBlobDescs()
    @     0x7f3e45480045  _ZNSt17_Function_handlerIFN7oneflow5MaybeIvvEEPNS0_8ExecNodeEEZZNKS0_5GraphIS3_NS0_8ExecEdgeEE15TopoForEachNodeERKNSt7__cxx114listIS4_SaIS4_EEERKSt8functionIFvS4_RKSF_IFvS4_EEEESN_SJ_ENKUlPKcE_clESP_EUlS4_E_E9_M_invokeERKSt9_Any_dataOS4_
    @     0x7f3e45482750  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x7f3e4548300c  oneflow::Graph<>::TopoForEachNode()
    @     0x7f3e454ee94c  oneflow::NormalForwardCompTaskNode::BuildExecGphAndRegst()
    @     0x7f3e454c6f25  _ZNSt17_Function_handlerIFN7oneflow5MaybeIvvEEPNS0_8TaskNodeEEZZNKS0_5GraphIS3_NS0_8TaskEdgeEE15TopoForEachNodeERKNSt7__cxx114listIS4_SaIS4_EEERKSt8functionIFvS4_RKSF_IFvS4_EEEESN_SJ_ENKUlPKcE_clESP_EUlS4_E_E9_M_invokeERKSt9_Any_dataOS4_
    @     0x7f3e454cbcaf  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x7f3e454cc3dc  oneflow::Graph<>::TopoForEachNode()
    @     0x7f3e4553db7b  oneflow::Compiler::Compile()
    @     0x7f3e45094414  oneflow::NNGraph::CompileAndInitRuntime()
    @     0x7f3e661fe84f  _ZZN8pybind1112cpp_function10initializeIZN7oneflowL24OneflowApiPythonModule45ERNS_7module_EEUlRNS2_7NNGraphEE3_vJS6_EJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESO_
    @     0x7f3e65b5bf97  pybind11::cpp_function::dispatcher()
    @     0x5613fd18b8b4  _PyMethodDef_RawFastCallKeywords
    @     0x5613fd18b9d1  _PyCFunction_FastCallKeywords
    @     0x5613fd1f827e  _PyEval_EvalFrameDefault
    @     0x5613fd13ad09  _PyEval_EvalCodeWithName
    @     0x5613fd13c01f  _PyFunction_FastCallDict
    @     0x5613fd15a7a3  _PyObject_Call_Prepend
    @     0x5613fd14d3ae  PyObject_Call
    @     0x5613fd1f4e97  _PyEval_EvalFrameDefault
    @     0x5613fd13ad09  _PyEval_EvalCodeWithName
    @     0x5613fd13c01f  _PyFunction_FastCallDict
    @     0x5613fd15a7a3  _PyObject_Call_Prepend
    @     0x5613fd191dea  slot_tp_call
    @     0x5613fd14d3ae  PyObject_Call
    @     0x5613fd1f4e97  _PyEval_EvalFrameDefault
    @     0x5613fd18ae2b  _PyFunction_FastCallKeywords
    @     0x5613fd1f36f0  _PyEval_EvalFrameDefault
F20220301 16:13:37.035899 52837 ctrl_client.cpp:54] Check failed: rpc_client_.GetStubAt(i)->CallMethod<CtrlMethod::kLoadServer>( &client_ctx, request, &response).error_code() == grpc::StatusCode::OK (14 vs. 0) Machine 0 lost
*** Check failure stack trace: ***
    @     0x7fd02405b64d  google::LogMessage::Fail()
    @     0x7fd02405d84c  google::LogMessage::SendToLog()
    @     0x7fd02405b0ea  google::LogMessage::Flush()
    @     0x7fd02405e229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd0281d0462  _ZZN7oneflow14GrpcCtrlClientC4ERKNS_10ProcessCtxEENKUlvE_clEv
    @     0x7fd023fc2447  execute_native_thread_routine
    @     0x7fd051ab2ea5  start_thread
    @     0x7fd0517db8dd  __clone
    Traceback (most recent call last):
  File "/home/chengpeng/data/anaconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chengpeng/data/anaconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chengpeng/data/oneflow/python/oneflow/distributed/launch.py", line 223, in <module>
    main()
  File "/home/chengpeng/data/oneflow/python/oneflow/distributed/launch.py", line 211, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/home/chengpeng/data/oneflow/python/oneflow/distributed/launch.py", line 180, in sigkill_handler
    returncode=last_return_code, cmd=cmd
subprocess.CalledProcessError: Command '['/home/chengpeng/data/anaconda3/envs/oneflow-dev-gcc7-v2/bin/python3', '-u', 'tools/train_net.py', '--config-file', 'configs/t5_pp_pretrain.py', 'train.dist.tensor_parallel_size=8', 'train.dist.pipeline_parallel_size=1', 'train.dist.data_parallel_size=1', 'train.zero_optimization.enabled=True', 'train.zero_optimization.stage=3', 'train.log_period=1']' died with <Signals.SIGABRT: 6>.
    F20220301 16:13:39.021886 52842 ctrl_client.cpp:54] Check failed: rpc_client_.GetStubAt(i)->CallMethod<CtrlMethod::kLoadServer>( &client_ctx, request, &response).error_code() == grpc::StatusCode::OK (14 vs. 0) Machine 0 lost
*** Check failure stack trace: ***
F20220301 16:13:39.023948 52841 ctrl_client.cpp:54] Check failed: rpc_client_.GetStubAt(i)->CallMethod<CtrlMethod::kLoadServer>( &client_ctx, request, &response).error_code() == grpc::StatusCode::OK (14 vs. 0) Machine 0 lost
*** Check failure stack trace: ***
    @     0x7f31bb78664d  google::LogMessage::Fail()
    @     0x7fba16dcd64d  google::LogMessage::Fail()
    @     0x7f31bb78884c  google::LogMessage::SendToLog()
    @     0x7fba16dcf84c  google::LogMessage::SendToLog()
    @     0x7f31bb7860ea  google::LogMessage::Flush()
    @     0x7fba16dcd0ea  google::LogMessage::Flush()
    @     0x7f31bb789229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fba16dd0229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f31bf8fb462  _ZZN7oneflow14GrpcCtrlClientC4ERKNS_10ProcessCtxEENKUlvE_clEv
    @     0x7fba1af42462  _ZZN7oneflow14GrpcCtrlClientC4ERKNS_10ProcessCtxEENKUlvE_clEv
    @     0x7f31bb6ed447  execute_native_thread_routine
    @     0x7fba16d34447  execute_native_thread_routine
    @     0x7f31e91ddea5  start_thread
    @     0x7fba44824ea5  start_thread
    @     0x7f31e8f068dd  __clone
    @     0x7fba4454d8dd  __clone
F20220301 16:13:39.281342 51725 rpc_client.cpp:40] Check failed: stub->CallMethod<ctrl_method>(&client_ctx, request_, &response_).error_code() == grpc::StatusCode::OK (14 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fbc52aba64d  google::LogMessage::Fail()
    @     0x7fbc52abc84c  google::LogMessage::SendToLog()
    @     0x7fbc52aba0ea  google::LogMessage::Flush()
    @     0x7fbc52abd229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbc56c454bf  oneflow::(anonymous namespace)::ClientCall<>::operator()()
    @     0x7fbc56c47428  oneflow::RpcClient::PullKV()
    @     0x7fbc56c4756a  oneflow::RpcClient::PullKV()
    @     0x7fbc5788d923  oneflow::NNGraph::CompileAndInitRuntime()
    @     0x7fbc789f784f  _ZZN8pybind1112cpp_function10initializeIZN7oneflowL24OneflowApiPythonModule45ERNS_7module_EEUlRNS2_7NNGraphEE3_vJS6_EJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESO_
    @     0x7fbc78354f97  pybind11::cpp_function::dispatcher()
    @     0x55e8a451a8b4  _PyMethodDef_RawFastCallKeywords
    @     0x55e8a451a9d1  _PyCFunction_FastCallKeywords
    @     0x55e8a458727e  _PyEval_EvalFrameDefault
    @     0x55e8a44c9d09  _PyEval_EvalCodeWithName
    @     0x55e8a44cb01f  _PyFunction_FastCallDict
    @     0x55e8a44e97a3  _PyObject_Call_Prepend
    @     0x55e8a44dc3ae  PyObject_Call
    @     0x55e8a4583e97  _PyEval_EvalFrameDefault
    @     0x55e8a44c9d09  _PyEval_EvalCodeWithName
    @     0x55e8a44cb01f  _PyFunction_FastCallDict
    @     0x55e8a44e97a3  _PyObject_Call_Prepend
    @     0x55e8a4520dea  slot_tp_call
    @     0x55e8a44dc3ae  PyObject_Call
    @     0x55e8a4583e97  _PyEval_EvalFrameDefault
    @     0x55e8a4519e2b  _PyFunction_FastCallKeywords
    @     0x55e8a45826f0  _PyEval_EvalFrameDefault
    @     0x55e8a4519e2b  _PyFunction_FastCallKeywords
    @     0x55e8a45826f0  _PyEval_EvalFrameDefault
    @     0x55e8a4519e2b  _PyFunction_FastCallKeywords
    @     0x55e8a4586ae9  _PyEval_EvalFrameDefault
    @     0x55e8a44c9fea  _PyEval_EvalCodeWithName
    @     0x55e8a451a0b7  _PyFunction_FastCallKeywords
F20220301 16:13:39.340955 51724 rpc_client.cpp:40] Check failed: stub->CallMethod<ctrl_method>(&client_ctx, request_, &response_).error_code() == grpc::StatusCode::OK (14 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fb5da14664d  google::LogMessage::Fail()
    @     0x7fb5da14884c  google::LogMessage::SendToLog()
    @     0x7fb5da1460ea  google::LogMessage::Flush()
    @     0x7fb5da149229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb5de2d14bf  oneflow::(anonymous namespace)::ClientCall<>::operator()()
    @     0x7fb5de2d3428  oneflow::RpcClient::PullKV()
    @     0x7fb5de2d356a  oneflow::RpcClient::PullKV()
    @     0x7fb5def19923  oneflow::NNGraph::CompileAndInitRuntime()
    @     0x7fb60008384f  _ZZN8pybind1112cpp_function10initializeIZN7oneflowL24OneflowApiPythonModule45ERNS_7module_EEUlRNS2_7NNGraphEE3_vJS6_EJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESO_
    @     0x7fb5ff9e0f97  pybind11::cpp_function::dispatcher()
    @     0x55a79b01f8b4  _PyMethodDef_RawFastCallKeywords
    @     0x55a79b01f9d1  _PyCFunction_FastCallKeywords
    @     0x55a79b08c27e  _PyEval_EvalFrameDefault
    @     0x55a79afced09  _PyEval_EvalCodeWithName
    @     0x55a79afd001f  _PyFunction_FastCallDict
    @     0x55a79afee7a3  _PyObject_Call_Prepend
    @     0x55a79afe13ae  PyObject_Call
    @     0x55a79b088e97  _PyEval_EvalFrameDefault
    @     0x55a79afced09  _PyEval_EvalCodeWithName
    @     0x55a79afd001f  _PyFunction_FastCallDict
    @     0x55a79afee7a3  _PyObject_Call_Prepend
    @     0x55a79b025dea  slot_tp_call
    @     0x55a79afe13ae  PyObject_Call
    @     0x55a79b088e97  _PyEval_EvalFrameDefault
    @     0x55a79b01ee2b  _PyFunction_FastCallKeywords
    @     0x55a79b0876f0  _PyEval_EvalFrameDefault
    @     0x55a79b01ee2b  _PyFunction_FastCallKeywords
    @     0x55a79b0876f0  _PyEval_EvalFrameDefault
    @     0x55a79b01ee2b  _PyFunction_FastCallKeywords
    @     0x55a79b08bae9  _PyEval_EvalFrameDefault
    @     0x55a79afcefea  _PyEval_EvalCodeWithName
    @     0x55a79b01f0b7  _PyFunction_FastCallKeywords
F20220301 16:13:39.610756 51729 rpc_client.cpp:40] Check failed: stub->CallMethod<ctrl_method>(&client_ctx, request_, &response_).error_code() == grpc::StatusCode::OK (14 vs. 0) 
F20220301 16:13:39.610755 51727 rpc_client.cpp:40] Check failed: stub->CallMethod<ctrl_method>(&client_ctx, request_, &response_).error_code() == grpc::StatusCode::OK (14 vs. 0) 
*** Check failure stack trace: ***
*** Check failure stack trace: ***
    @     0x7fca0fbb764d  google::LogMessage::Fail()
    @     0x7ffaa976464d  google::LogMessage::Fail()
    @     0x7fca0fbb984c  google::LogMessage::SendToLog()
    @     0x7ffaa976684c  google::LogMessage::SendToLog()
    @     0x7fca0fbb70ea  google::LogMessage::Flush()
    @     0x7ffaa97640ea  google::LogMessage::Flush()
    @     0x7fca0fbba229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ffaa9767229  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fca13d424bf  oneflow::(anonymous namespace)::ClientCall<>::operator()()
    @     0x7ffaad8ef4bf  oneflow::(anonymous namespace)::ClientCall<>::operator()()
    @     0x7fca13d44428  oneflow::RpcClient::PullKV()
    @     0x7ffaad8f1428  oneflow::RpcClient::PullKV()
    @     0x7fca13d4456a  oneflow::RpcClient::PullKV()
    @     0x7ffaad8f156a  oneflow::RpcClient::PullKV()
    @     0x7fca1498a923  oneflow::NNGraph::CompileAndInitRuntime()
    @     0x7ffaae537923  oneflow::NNGraph::CompileAndInitRuntime()
    @     0x7fca35af484f  _ZZN8pybind1112cpp_function10initializeIZN7oneflowL24OneflowApiPythonModule45ERNS_7module_EEUlRNS2_7NNGraphEE3_vJS6_EJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESO_
    @     0x7ffacf6a184f  _ZZN8pybind1112cpp_function10initializeIZN7oneflowL24OneflowApiPythonModule45ERNS_7module_EEUlRNS2_7NNGraphEE3_vJS6_EJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESO_
    @     0x7fca35451f97  pybind11::cpp_function::dispatcher()
    @     0x5637465478b4  _PyMethodDef_RawFastCallKeywords
    @     0x7ffaceffef97  pybind11::cpp_function::dispatcher()
    @     0x5637465479d1  _PyCFunction_FastCallKeywords
    @     0x5591208778b4  _PyMethodDef_RawFastCallKeywords
    @     0x5637465b427e  _PyEval_EvalFrameDefault
    @     0x5591208779d1  _PyCFunction_FastCallKeywords
    @     0x5637464f6d09  _PyEval_EvalCodeWithName
    @     0x5591208e427e  _PyEval_EvalFrameDefault
    @     0x5637464f801f  _PyFunction_FastCallDict
    @     0x559120826d09  _PyEval_EvalCodeWithName
    @     0x5637465167a3  _PyObject_Call_Prepend
    @     0x55912082801f  _PyFunction_FastCallDict
    @     0x5637465093ae  PyObject_Call
    @     0x5591208467a3  _PyObject_Call_Prepend
    @     0x5637465b0e97  _PyEval_EvalFrameDefault
    @     0x5591208393ae  PyObject_Call
    @     0x5637464f6d09  _PyEval_EvalCodeWithName
    @     0x5591208e0e97  _PyEval_EvalFrameDefault
    @     0x5637464f801f  _PyFunction_FastCallDict
    @     0x559120826d09  _PyEval_EvalCodeWithName
    @     0x5637465167a3  _PyObject_Call_Prepend
    @     0x56374654ddea  slot_tp_call
    @     0x55912082801f  _PyFunction_FastCallDict
    @     0x5637465093ae  PyObject_Call
    @     0x5591208467a3  _PyObject_Call_Prepend
    @     0x55912087ddea  slot_tp_call
    @     0x5637465b0e97  _PyEval_EvalFrameDefault
    @     0x5591208393ae  PyObject_Call
    @     0x563746546e2b  _PyFunction_FastCallKeywords
    @     0x5591208e0e97  _PyEval_EvalFrameDefault
    @     0x5637465af6f0  _PyEval_EvalFrameDefault
    @     0x559120876e2b  _PyFunction_FastCallKeywords
    @     0x563746546e2b  _PyFunction_FastCallKeywords
    @     0x5591208df6f0  _PyEval_EvalFrameDefault
    @     0x5637465af6f0  _PyEval_EvalFrameDefault
    @     0x559120876e2b  _PyFunction_FastCallKeywords
    @     0x563746546e2b  _PyFunction_FastCallKeywords
    @     0x5591208df6f0  _PyEval_EvalFrameDefault
    @     0x5637465b3ae9  _PyEval_EvalFrameDefault
    @     0x559120876e2b  _PyFunction_FastCallKeywords
    @     0x5637464f6fea  _PyEval_EvalCodeWithName
    @     0x5591208e3ae9  _PyEval_EvalFrameDefault
    @     0x559120826fea  _PyEval_EvalCodeWithName
    @     0x5637465470b7  _PyFunction_FastCallKeywords
    @     0x5591208770b7  _PyFunction_FastCallKeywords
```
</details>

**Comment by ouyangyu** [comment]
> t_return_code, cmd=cmd
> subprocess.CalledProcessError: Command '['/home/chengpeng/data/anaconda3/envs/oneflow-dev-gcc7-v2/bin/python3', '-u', 'tools/train_net.py', '--config-file', 'configs/t5_pp_pretrain.py', 'train.dist.tensor_parallel_size=8', 'train.dist.pipeline_parallel_size=1', 'train.dist.data_parallel_size=1', 'train.zero_optimization.enabled=True', 'train.zero_optimization.stage=3', 'train.log_period=1']' died with <Signals.SIGABRT: 6>.
>     F20220301 16:13:39.021886 52842 ctrl_client.cpp:54] Check failed: rpc_client_.GetStubAt(i)->CallMethod<CtrlMethod::kLoadServer>( &client_ctx, request, &response).error_code() == grpc::StatusCode::OK (14 vs. 0) Machine 0 lost
> *** Check failure stack trace: ***
> F20220301 16:13:39.023948 52841 ctrl_client.cpp:54] Check failed: rpc_client_.GetStubAt(i)->CallMethod<CtrlMethod::kLoadServer>( &client_ctx, request, &response).error_code() == grpc::StatusCode::OK (14 vs. 0) Machine 0 lost
> *** Check failure stack trace: ***
>     @     0x7f31bb78664d  google::LogMessage::Fail()
>     @     0x7fba16dcd64d  google::LogMessage::Fail()
>     @     0x7f31bb78884c  google::LogMessage::SendToLog()
>     @     0x7fba16dcf84c  google::LogMessage::SendToLog()
>     @     0x7f31bb7860ea  google::LogMessage::Flush()
>     @     0x7fba16dcd0ea  google::LogMessage::Flush()
>     @     0x7f31bb789229  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7fba16dd0229  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f31bf8fb462  _ZZN7oneflow14GrpcCtrlClientC4ERKNS_10ProcessCtxEENKUlvE_clEv
>     @     0x7fba1af42462  _ZZN7oneflow14GrpcCtrlClientC4ERKNS_10ProcessCtxEENKUlvE_clEv
>     @     0x7f31bb6ed447  execute_native_thread_routine
>     @     0x7fba16d34447  execute_native_thread_routine
>     @     0x7f31e91ddea5  start_thread
>     @     0x7fba44824ea5  start_thread
>     @     0x7f31e8f068dd  __clone
>     @     0x7fba4454d8dd  __clone
> F20220301 16:13:39.281342 51725 rpc_client.cpp:40] Check failed: stub->CallMethod<ctrl_method>(&client_ctx, request_, &response_).error_code() == grpc::StatusCode::OK (14 vs. 0)

这个属于上一个连接还没释放吧，过一会再跑呢？

**Comment by CPFLAME** [comment]
> 这个属于上一个连接还没释放吧，过一会再跑呢？

一样的, 还是有这个错误.  我感觉可能是多卡的报错导致了这个输出信息?

**Comment by ouyangyu** [comment]
> > 这个属于上一个连接还没释放吧，过一会再跑呢？
> 
> 一样的, 还是有这个错误. 我感觉可能是多卡的报错导致了这个输出信息?

看错了，具体错误应该是这个：
```
F20220301 08:31:15.972954 77402 exec_graph.cpp:117]
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/graph/exec_graph.cpp", line 117, in InferBlobDescs
    op_->InferBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx, &GlobalJobDesc())
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/operator/operator.cpp", line 324, in InferBlobDescsIf
    InferOutBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/operator/user_op.cpp", line 599, in InferOutBlobDescs
    val_->physical_tensor_desc_infer_fn(&infer_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/user/ops/reshape_op.cpp", line 101, in InferPhysicalTensorDesc
    Check failed: (out_shape->elem_cnt()) == (in_shape.elem_cnt()) (1572864 vs 2359296)  Reshape infer ERROR! in op_name: model.t5_model.encoder.layers.0.self_attention-reshape-25 input shape is : (32,512,144) , output shape is : (32,512,1,96) , output logical shape is (32,512,12,96) , And reshape shape conf is : (32,512,12,96) op_loc: Python stack[-2]: <frame at 0x56054967e450, file '/home/ylkj/miniconda3/lib/python3.7/site-packages/oneflow/framework/tensor.py', line 917, code _view>; Python stack[-1]: <frame at 0x56054966bc20, file '/home/ylkj/miniconda3/lib/python3.7/site-packages/oneflow/nn/modules/reshape.py', line 68, code view_op>; C API: <func reshape>
```

**Comment by L1aoXingyu** [comment]
是不是 zero 应该搭配数据并行使用，模型并行本身就不应该一起用

**Comment by CPFLAME** [comment]
稍等一下 我更新一下实验配置, 做一下更详尽的实验

**Comment by CPFLAME** [comment]
我直接在comment上修改了, 可以看一下最新的信息 https://github.com/Oneflow-Inc/libai/issues/150#issuecomment-1055148111

**Comment by CPFLAME** [comment]
测试了本分支在T5上, 各种配置的表现.
其中开启checkpointing+纯数据并行 应该是综合性能最优的选择(实验3和实验6)

T5上的实验数据
|    | **打开checkpointing, batch_size=32**   | 吞吐 | 0卡显存 | 1卡显存 | 2卡显存 | 3卡显存 | 4卡显存 | 5卡显存 | 6卡显存 | 7卡显存 |
| -- | ------------------------------------ | ------ | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- |
| 1  | 数据并行2+模型并行2+流水并行2 | 36.38  | 4509MiB | 4607MiB | 4547MiB | 4615MiB | 4477MiB | 4495MiB | 4489MiB | 4503MiB |
| 2  | 数据并行4+模型并行2          | 74.03  | 6093MiB | 6191MiB | 6141MiB | 6207MiB | 6141MiB | 6205MiB | 6141MiB | 6207MiB |
| 3  | 数据并行8                        | 383.10 | 4103MiB | 4135MiB | 4087MiB | 4149MiB | 4135MiB | 4185MiB | 4165MiB | 4127MiB |
| 4  | 数据并行8+zero_stage=2           | 342.61 | 3717MiB | 3799MiB | 3995MiB | 3909MiB | 3763MiB | 3771MiB | 3731MiB | 3747MiB |
| 5  | 数据并行8+zero_stage=2+batch_size=16 | 289.02 | 2765MiB | 2875MiB | 2793MiB | 2779MiB | 2793MiB | 2765MiB | 2775MiB | 2801MiB |
|    | **关闭Checkpointing, batch_size=16**   |        |         |         |         |         |         |         |         |         |
| 6  | 数据并行8                        | 447.14 | 8217MiB | 8383MiB | 8217MiB | 8249MiB | 8383MiB | 8383MiB | 8249MiB | 8249MiB |
| 7  | 数据并行4+模型并行2          | 86.57  | 6761MiB | 6825MiB | 6809MiB | 6841MiB | 6809MiB | 6829MiB | 6809MiB | 6841MiB |
| 8  | 数据并行2+模型并行2+流水并行2 | 46.33  | 4537MiB | 4601MiB | 4615MiB | 4709MiB | 3559MiB | 3579MiB | 3579MiB | 3579MiB |
| 9  | 数据并行8+zero_stage=2           | 344.63 | 7873MiB | 7905MiB | 7905MiB | 7905MiB | 7905MiB | 8041MiB | 7905MiB | 7905MiB |
| 10 | 数据并行8+zero_stage=3           | 332.75 | 7999MiB | 8031MiB | 8167MiB | 8031MiB | 8167MiB | 8031MiB | 8031MiB | 8031MiB |

在bert上测试了2d sbp的表现,  和最新的nightly比较了一下, 吞吐和显存没有明显变化
nightly版本信息:
```
version: 0.7.0.dev20220301+cu102
git_commit: 6946b48
cmake_build_type: Release
rdma: True
mlir: True
```
| 数据并行4+模型并行2 +batch_size=8| 吞吐 | 显存  |
| ------------------- | ----- | ------- |
| nightly             | 17.44 | 9621MiB |
| fix_sbp_error       | 17.41 | 9587MiB |
