### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'flags'

### ISSUE THREAD

**Issue by michelleqyhqyh** [Oneflow-Inc/libai#463]
I want to tun T5 example. This is my command. But there is an error. How can I fix it?

export CUDA_VISIBLE_DEVICES=2,3
bash tools/train.sh tools/train_net.py projects/T5/configs/mt5_pretrain.py 2

bash: /home/qyh/anaconda3/envs/syl-env/lib/libtinfo.so.6: no version information available (required by bash)
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/resources/qyh/big-model/libai/tools/train_net.py", line 25, in <module>
    from libai.config import LazyConfig, default_argument_parser, try_get_key
  File "/resources/qyh/big-model/libai/libai/__init__.py", line 20, in <module>
    from libai import data
  File "/resources/qyh/big-model/libai/libai/data/__init__.py", line 17, in <module>
    from .build import (
  File "/resources/qyh/big-model/libai/libai/data/build.py", line 35, in <module>
    train_sampler=LazyCall(CyclicSampler)(shuffle=True),
  File "/resources/qyh/big-model/libai/libai/config/lazy.py", line 123, in __call__
    return DictConfig(content=kwargs, flags={"allow_objects": True})
TypeError: __init__() got an unexpected keyword argument 'flags'
Traceback (most recent call last):
  File "/resources/qyh/big-model/libai/tools/train_net.py", line 25, in <module>
    from libai.config import LazyConfig, default_argument_parser, try_get_key
  File "/resources/qyh/big-model/libai/libai/__init__.py", line 20, in <module>
    from libai import data
  File "/resources/qyh/big-model/libai/libai/data/__init__.py", line 17, in <module>
    from .build import (
  File "/resources/qyh/big-model/libai/libai/data/build.py", line 35, in <module>
    train_sampler=LazyCall(CyclicSampler)(shuffle=True),
  File "/resources/qyh/big-model/libai/libai/config/lazy.py", line 123, in __call__
    return DictConfig(content=kwargs, flags={"allow_objects": True})
TypeError: __init__() got an unexpected keyword argument 'flags'
Killing subprocess 4172867
Killing subprocess 4172868
Traceback (most recent call last):
  File "/home/qyh/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/qyh/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/qyh/anaconda3/envs/py39/lib/python3.9/site-packages/oneflow/distributed/launch.py", line 240, in <module>
    main()
  File "/home/qyh/anaconda3/envs/py39/lib/python3.9/site-packages/oneflow/distributed/launch.py", line 228, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/home/qyh/anaconda3/envs/py39/lib/python3.9/site-packages/oneflow/distributed/launch.py", line 196, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/home/qyh/anaconda3/envs/py39/bin/python3', '-u', 'tools/train_net.py', '--config-file', 'projects/T5/configs/mt5_pretrain.py']' returned non-zero exit status 1.

**Comment by xiezipeng-ML** [comment]
check your omegaconf version==2.1.0？

**Comment by xiezipeng-ML** [comment]
可以安装一下最新的oneflow：`python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu116`
然后libai用`pip install -e .`的方式来安装试试呢

**Comment by michelleqyhqyh** [comment]
1. 我用一块GPU完成了T5的训练，但是T5的模型参数量不是110亿吗？用一块V100怎么会加载完这么大的模型?
2. 我训练完之后该用怎么代码来测试效果呀？

**Comment by xiezipeng-ML** [comment]
> 1. 我用一块GPU完成了T5的训练，但是T5的模型参数量不是110亿吗？用一块V100怎么会加载完这么大的模型?

可以确认一下自己训练的时候用的什么规模的模型配置

> 2. 我训练完之后该用怎么代码来测试效果呀？

libai里和其他的库比如megatron提供的都是模型的预训练任务，所以测试效果可以在测试集上跑一下预训练任务的指标，如果希望训练出完整的T5，也就是达到libai中利用T5权重做推理任务的话，还需要在多个下游任务上finetune预训练模型后测试效果

@michelleqyhqyh
